name: Release
run-name: Release

on:
  workflow_dispatch:

permissions:
    contents: write

jobs:
  prepare_release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7.0.0
      - name: Create empty release
        id: release
        uses: softprops/action-gh-release@v3.0.0
        with:
          tag_name: v2.4.2
          token: ${{ secrets.GITHUB_TOKEN }}
          target_commitish: main
          draft: true
    outputs:
      release_id: ${{ steps.release.outputs.id }}

  config:
    runs-on: ubuntu-latest
    name: Create martrix
    outputs:
      build_matrix: ${{ steps.build.outputs.build_matrix }}
      rootfs_matrix: ${{ steps.rootfs.outputs.rootfs_matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v7.0.0

      - name: Create build matrix
        id: build
        run: |
            build_matrix=""
            for file in config/boards/*; do
                COMPATIBLE_SUITES=()
                COMPATIBLE_FLAVORS=()
                # shellcheck disable=SC1090
                source "${file}"
                for suite in "${COMPATIBLE_SUITES[@]}"; do
                    [ "${suite}" = "noble" ] || continue   # release noble (24.04) only
                    for flavor in "${COMPATIBLE_FLAVORS[@]}"; do
                    build_matrix+="{\"board\":\"$(basename "${file%.sh}")\",\"suite\":\"${suite}\",\"flavor\":\"${flavor}\"},"
                    done
                done
            done
            echo "build_matrix={\"include\":[${build_matrix::-1}]}" >> $GITHUB_OUTPUT

      - name: Create rootfs matrix
        id: rootfs
        run: |
            rootfs_matrix=""
            for suite in config/suites/*; do
                [ "$(basename "${suite%.sh}")" = "noble" ] || continue   # release noble (24.04) only
                for flavor in config/flavors/*; do
                    rootfs_matrix+="{\"suite\":\"$(basename "${suite%.sh}")\",\"flavor\":\"$(basename "${flavor%.sh}")\"},"
                done
            done
            echo "rootfs_matrix={\"include\":[${rootfs_matrix::-1}]}" >> $GITHUB_OUTPUT

  rootfs:
    runs-on: [self-hosted, ARM64, RK1]
    name: Build rootfs
    needs: [prepare_release, config]
    strategy:
        matrix: ${{ fromJson(needs.config.outputs.rootfs_matrix) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v7.0.0

      - name: Set environment variables
        id: vars
        run: |
          source config/suites/${{ matrix.suite }}.sh
          echo "suite_version=$RELASE_VERSION" >> $GITHUB_OUTPUT

      - name: Build
        shell: bash
        run: sudo ./build.sh --suite=${{ matrix.suite }} --flavor=${{ matrix.flavor }} --rootfs-only --launchpad

      - name: Upload
        uses: actions/upload-artifact@v7.0.1
        with:
            name: ubuntu-${{ steps.vars.outputs.suite_version }}-preinstalled-${{ matrix.flavor }}-arm64-rootfs
            path: ./build/ubuntu-${{ steps.vars.outputs.suite_version }}-preinstalled-${{ matrix.flavor }}-arm64.rootfs.tar.xz
            if-no-files-found: error

  build:
    runs-on: [self-hosted, ARM64, RK1]
    needs: [rootfs, prepare_release, config]
    name: Build image 
    strategy:
        matrix: ${{ fromJson(needs.config.outputs.build_matrix) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v7.0.0

      - name: Set environment variables
        id: vars
        run: |
          source config/suites/${{ matrix.suite }}.sh
          echo "suite_version=$RELASE_VERSION" >> $GITHUB_OUTPUT

      - name: Checkout rootfs
        uses: actions/download-artifact@v8.0.1
        with:
            name: ubuntu-${{ steps.vars.outputs.suite_version }}-preinstalled-${{ matrix.flavor }}-arm64-rootfs
            path: ./build/

      - name: Build
        shell: bash
        run: sudo ./build.sh --board=${{ matrix.board }} --suite=${{ matrix.suite }} --flavor=${{ matrix.flavor }} --launchpad

      - name: Upload
        if: needs.prepare_release.outputs.release_id != '' 
        uses: xresloader/upload-to-github-release@v1.6.2
        env:
            GITHUB_TOKEN:  ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ needs.prepare_release.outputs.release_id }}
          file: images/ubuntu-*-preinstalled-*-arm64-${{ matrix.board }}.*
          draft: true
          overwrite: true

      - name: Clean cache
        shell: bash
        run: sync && sudo rm -rf ./images/ ./build/ && sync
